### ISSUE TITLE
escaped sequences preferred in css

### ISSUE THREAD

**Issue by krisbulman** [danielbruce/entypo#1]
I have a question about the decision about using UTF-8 chars instead of css escape sequences in 85ecac67252bb33c5ac1a490d9989fdd69403136 

I have had no problems displaying these icons using css escape sequences in FF, Safari, or Chrome (commit 16cfc6a38cae40ccdcedc3b4e353e2da24e3679a ). 

Besides, wouldn't using special characters force us to use the @charset rule? http://reference.sitepoint.com/css/at-charset

Instead, this css method could be used:

```
content: "\2665"; /* ♥ */
```

and expressions can be added for earlier IE support 

further reading: 
http://coding.smashingmagazine.com/2011/03/19/styling-elements-with-glyphs-sprites-and-pseudo-elements/

Perhaps this has already been thought out, so just looking for some explanation on why that route was chosen.

**Comment by puzrin** [comment]
2-bytes codes are ok, but 3-bytes are broken with escaped chars. Check out https://github.com/danielbruce/entypo/commit/74472c251741e0d1acecba716495fe297708a172 in chrome/opera, and you will see what i mean. Pay attention to symbols `1Fxxx`.

Smashmag issue doesn't pay attention to 3-bytes chars.

**Comment by puzrin** [comment]
I close this issue, since we can do nothing with it.

Currently:
- firefox ok
- opera ok
- chrome fails to works with 3-byte escape chars.
