### ISSUE TITLE
Entypo2 Only Rendering in Chrome

### ISSUE THREAD

**Issue by cdukes** [danielbruce/entypo#12]
I'm unable to use the new version of Entypo in FF, iOS, or IE. The old version hosted by Font Squirrel works fine, but when I drop in the 4 font files for the new version (keeping all file names, changing nothing but the files themselves), the fonts don't load correctly. See site: blog.inneosg.com

Any assistance is appreciated.

**Comment by danielbruce** [comment]
> I'm unable to use the new version of Entypo in FF, iOS, or IE. The old version hosted by Font Squirrel works fine, but when I drop in the 4 font files for the new version (keeping all file names, changing nothing but the files themselves), the fonts don't load correctly. See site: blog.inneosg.com
> 
> Any assistance is appreciated.

Hi there,

yes. You need to change your code to go with the new location of the characters. Check the map on entypo.com or the RTF file in the downloaded package.

Cheers

–

Daniel Bruce  |  Creative
A good idea is to follow me on Twitter and Dribbble.

**Comment by cdukes** [comment]
Gotcha. Thanks!
