### ISSUE TITLE
Icons show up randomly and often not 

### ISSUE THREAD

**Issue by universaldenmark** [danielbruce/entypo#17]
I'm having huge issues working with these beautiful icons. I've inserted them as both entypo-classes and in other classes through the "content:" function.

However some icons works, some dont. And mostly in other browsers but Chrome they dont. Is there a best practise about these icons, so they're consistent on all platforms?

**Comment by forgegod** [comment]
Give https://github.com/danielbruce/entypo/issues/14#issuecomment-19171286 a try

**Comment by universaldenmark** [comment]
Can you explain what it does different? And why it works? :)

**Comment by forgegod** [comment]
Some of the characters/icons are UTF-16 (character/icon code greater then 65535)

**Comment by universaldenmark** [comment]
Hmmm that screwed up the site completely: http://www.cphrecmedia.dk/musikdk/stage/
See the star in the top, it uses the same class as the one to the right, but is twice the size.
And many fonts still don't show up

**Comment by forgegod** [comment]
Hmm. You are using our own CSS definitions for the icons e.g. `entypo-home`

Open the demo.html from https://github.com/RaphaelBossek/entypo/blob/master/font.zip and verify if your icons are there. You should use the automaticaly generated `entypo.css` and its icon name definitions `<span class="font-entypo icon-home"></span>`

**Comment by universaldenmark** [comment]
Ahh when I tested it, I put a dot before the span :l Now it works fine :) However I've tried to insert one in a new non-span class, so I can have a arrow on all of my next buttons. This wont however work. It looks like this:

btnnewstags:before, .btntags:before{
    content:'\e762';
    padding-right: 5px;
}

Why wont this work when all other "content:" works?

**Comment by forgegod** [comment]
Because your CSS is invalid? btnnewstags -> .btnnewstags

Please use http://jsfiddle.net/ to post code snippets here

**Comment by universaldenmark** [comment]
Sorry here's code on JSFiddle: http://jsfiddle.net/aPQ7a/ (new colors as I use LESS).
Sorry its properly a dummy mistake I've blinded myself on, but where do you see the invalid CSS?
I have dots in all of my css

**Comment by forgegod** [comment]
Ok. Here is the code http://jsfiddle.net/aPQ7a/1/ With LESS you can also mixin the font-entypo and icon-\* definition into .btnnewstags:before, .btntags:before so you do not have to worry if the codes or font defintion changes.

**Comment by universaldenmark** [comment]
I must have an error on my site, cos your code works perfectly, but when I copy paste the code into my site, it wont work :l I have to look some more, but I thank you very very much for the help!

**Comment by universaldenmark** [comment]
Sorry Raphael, to annoy you again, but I really cant get it to work :l If I copy-paste in the working jsfiddle code to my site, some icons wont show up. Do you know any reason for this to happen?

**Comment by forgegod** [comment]
You have to reveal me a little bit more where (URL) the problem exists.

**Comment by universaldenmark** [comment]
Ahh sorry.
http://www.cphrecmedia.dk/musikdk/stage/remix.php
The tags to the left has a star, but if you try to change that to the tag-icon directly in the Inspector, you'll get a rounded box and not the right tag. The same thing will happen if I copy-paste in the working code from JsFiddle

**Comment by forgegod** [comment]
You are using the UNICODE character "black star" (http://www.fileformat.info/info/unicode/char/2605/index.htm) but not from the Entypo font-face. In the JsFidle example I wrote `class="font-entypo btntags"` but it would be better to say:
`.btnnewstags:before, .btntags:before {
  font-family: 'entypo';
  speak: none;
  content: "\x2605";
  padding-right: 5px;
}`

**Comment by universaldenmark** [comment]
Ahhh that helped. Sorry for being to newbie! Really appriciated the help!
