### ISSUE TITLE
Problem showing icons on firefox

### ISSUE THREAD

**Issue by simo2409** [danielbruce/entypo#23]
Hi,
I'm having problems with all entypo icons in Firefox but probably there is something broken on my side which I can't figure out.

Viewing the page locally everything works as normal but when I put everything online I can't see icons on Firefox (Chrome works properly).

On the server I'm using nginx which serves icons with correct mime type.
In html I specified meta charset to "utf-8".
In Firebug I see there is no 404s (so browser can find entypo font)

Does anybody have an idea of what can be broken?

The output is like this for all icons:
![schermata 2014-05-31 alle 10 39 27](https://cloud.githubusercontent.com/assets/3965/3138610/1b40f898-e89f-11e3-9ec5-feb3d427bc53.png)

Thank you

**Comment by simo2409** [comment]
Finally I got it, I had to enable CORS in nginx for font files (if you know what to google the solution is very quick, just google "nginx enable CORS")

Thank you for your work with entypo!

**Comment by abdulbasitnawab** [comment]
Thanks simo2409 for answering it, I spend a lot of time fixing this issue, But finally your post helped me,

**Comment by abdulbasitnawab** [comment]
You may find this php code handy
 <?php
 header("Access-Control-Allow-Origin: *");
?>
