### ISSUE TITLE
Finalize CSS icon names

### ISSUE THREAD

**Issue by puzrin** [danielbruce/entypo#3]
There is some difference between original file names / bootstrap / semantic. Decide, wich one is preferable, and should be promoted to another iconic fonts.

**Comment by danielbruce** [comment]
Now back from my eastern holiday. 

I think we should put it to the vote in some way. If we want to come up with a standardized way to name pictograms it is difficult to make the decisions be your self. What do you think is the best way forward?

**Comment by puzrin** [comment]
If you are not fine with some name - write me details. Please, note, that i've added search synonyms in config file, to make effective search possible https://github.com/danielbruce/entypo/blob/master/config.yml

**Comment by danielbruce** [comment]
Ok. I've been thinking and thinking over here. I'm working on a list of the names i prefer and as you have done I think it should be a main name and several synonyms. I'm also thinking about how to proceed with the next version of Entypo and the site. With this superb auto generated solution do I really need a classic font and character map on the site?! Shouldn't it just be like the pictos server? If so it's easier to add new glyphs over time. And with a solution like that it would me nice to have all the names and synonyms visible so you can search for a glyph as well.  Once again, what's your take on this?

Damn I need more time :)

**Comment by puzrin** [comment]
http://fontello.com/ (fontomas v2 preview) - i tryed to be "good for all". First tab allows easy selection/navigation. Second tab show how symbols look in real life - it's significant for developpers. Search is missed, but will be added later. I don't see reasons to show all synonyms. It doesn't matter, and will clutter interface. The main practical reason of second tab - to show glyph scale/alligment, and how symbols are coded in css.

But Fontello and Entypo could have different goals. I have no reasons to promote myself as designer, and fontello as artwork :) . It's just convenient technical instrument for technical people (yes, it's horrible designed, but still convenient). So, Entypo's site content can have big differences.

Anyway, if you need help with templates for your site - let me know. I'll try to help about automating process, when you add new glyphs.

**Comment by danielbruce** [comment]
Looks awesome! But isn't better if one has the option to rearrange the glyphs like on fontomas. I agree that you don't have to show all synonyms as long as you can search for them and that they will show up on a google search. An automated process for adding new glyphs would be über great.

I do not see big differences in functionality for the Entypo site but a little tweaking of the design and of cause some added information. I would be ever grateful if you liked to help out on it together with me and my front end programming friend Andreas. Entypo for me is 1. a way to contribute to the community and 2. a way to promote myself as a designer. Getting more followers on twitter or dribble is a reward in it self.

One last thing. Can you please remove the suitcase with two buckles? That was just a sketch. 

Cheers man and once again awesome work!

**Comment by puzrin** [comment]
> But isn't better if one has the option to rearrange the glyphs like on fontomas
1. You can edit glyph codes on download tab. Just click in glyph header/footer. That's just preview, and we not yet solved some usability issues. Drag&Drop on previous version had effective look, but was a bit useless :)
2. Generic glyphs order in font is defined by config file. It's not a problem to change, if you need another order, but i don't see reasons to expose such option for all.

**Comment by danielbruce** [comment]
1. Well I think you should make this more obvious. For a designer who uses the font in Photoshop or Illustrator they would prefer to pick out the icons they want to use for this project and then have them assigned to easy accessible keys like a, s, d, f etc. I understand it doesn't matter to a programmer. If a simple map of my selected glyphs came with the download that a designer then can pass on to a developer it would be great as well.
2. I agree on that.

**Comment by puzrin** [comment]
Scheduled: https://github.com/nodeca/fontomas/issues/35

**Comment by danielbruce** [comment]
I've started to design Fontomas on paper since—in my opinion—I would rethink some parts of UI. From a usability perspective it is not perfect right now. For example I would rename the steps to "1. Select" and "2. Rearrange & download". No third step.

I would also make it more clear that you can change the character assigned to each glyph as well as add the HTML Entity (hex). Exactly what information will be in the downloaded font? Name, license, author? 

Also, it might be an idea to be able to name the font before downloading. For example (on Entypo) it would be great to name my font after the project I'm working on but always with the name Entypo first. Like my font will be named "entypo-project-x". This will help users keep track of their fronts.

**Comment by puzrin** [comment]
> I've started to design Fontomas on paper since—in my opinion—I would rethink some parts of UI. From a usability perspective it is not perfect right now. For example I would rename the steps to "1. Select" and "2. Rearrange & download". No third step.

User should see text preview + be able to edit glyph codes. I don't care about steps count, if you know, how to make convenient interface :) .

> I would also make it more clear that you can change the character assigned to each glyph as well as add the HTML Entity (hex).

Yes. Just note, that current demo is a mockup, to show that "feature exists" & how it work. We are concentrated on software, it still needs a lot of work.

> Exactly what information will be in the downloaded font? Name, license, author?

I think to add file with licence info about all used fonts. If you have better idea - let me know. User will download ZIP-archive with content of this folder https://github.com/danielbruce/entypo/tree/master/font + lisence file.

> Also, it might be an idea to be able to name the font before downloading. For example (on Entypo) it would be great to name my font after the project I'm working on but always with the name Entypo first. Like my font will be named "entypo-project-x". This will help users keep track of their fronts.

May be. That's about session management. I think, it's better to postpone it until v3. Or until 2.1. I really need to release fontello (fontomas v2.0) as soon as possible. Anyway, feel free to add any tickets to fontomas issue tracker.

**Comment by puzrin** [comment]
Done
