### ISSUE TITLE
OS X Opera 11.6 - not rendering font

### ISSUE THREAD

**Issue by krisbulman** [danielbruce/entypo#5]
Fonts do not render in Opera 11.6 on OS X Lion. 

**Upd** This is OS X specific. No problems under win/linux

Error console

```
[1 April, 2012 10:59:13 PM] Internal - /entypo/font/entypo.eot?

webfont discarded - malformed
[1 April, 2012 10:59:13 PM] Internal - /entypo/font/entypo.woff

Unable to use webfont
[1 April, 2012 10:59:13 PM] Internal - /entypo/font/entypo.ttf

Unable to use webfont
[1 April, 2012 10:59:13 PM] XML - /entypo/font/entypo.svg
Tag at line 3, column 0 to line 3, column 5
Warning: default XML namespace declaration attribute present in external DTD
subset but not specified in document.  To ensure compatibility with non-
validating XML parsers, XML namespace declarations should be declared in the
internal DTD subset or be specified in the element start tag.
  Element name: svg
  Attribute: xmlns="http://www.w3.org/2000/svg"
```

**Comment by puzrin** [comment]
Do you look page via http or from file system? Opera doesn't support fs.

Under linux you can use [thttp](http://acme.com/software/thttpd/) to proxy local dir. Don't know about macos

**Comment by puzrin** [comment]
Is it specific OS X issue ? Refreshed demo page to include woff

I've installed Opera 11.60 under Ubuntu, and it's ok.

**Comment by krisbulman** [comment]
Tested on a local apache setup through MAMP using wildcard DNS.

It does work in my Ubuntu instance, and it does work in Windows.  

is there a gh-pages set up with the demo code?

**Comment by puzrin** [comment]
`make gh-pages` should help. See `./Makefile` source for all goodies.

It just copies `./font` folder to `gh-pages` branch.

**Comment by krisbulman** [comment]
k, tested on github pages on a macbook pro, and macpro, both with Opera 11.6. This is a confirmed OS X specific Opera issue. I will have to check back a few revisions though, i thought i recalled this working in Opera once.

**Comment by puzrin** [comment]
http://fortawesome.github.com/Font-Awesome/

Does that one also have problems under opera in osx ?

**Comment by krisbulman** [comment]
No, the icons there load fine

**Comment by puzrin** [comment]
Hm... probably, there is something critical in font headers, that i stripped as useless.

Please, test this demo from iconic https://github.com/somerandomdude/Iconic/tree/master/font/Iconic%20Fill . It's generated in similar way, but with more headers params https://github.com/somerandomdude/Iconic/blob/master/scripts/font%20creation/blank_fill.sfd .

**Comment by krisbulman** [comment]
Yes, both demos work in Opera 11.06/OS X (fill and stroke)

**Comment by puzrin** [comment]
Great! That means, that i have to roll back ripped headers, and then remove one-by-one, until we find where is a problem.

**Comment by krisbulman** [comment]
is the sfd template file not required in this release? I don't see it in the entypo repo

**Comment by puzrin** [comment]
It's not needed, It just contained pre-defined values, that were moved to config in "font" section.

https://github.com/danielbruce/entypo/commit/2549b91a8e6012da815636b19398ae0e92496de3

I've reduced number of parameters, but seems that osx opera need some.

**Comment by puzrin** [comment]
Fixed

https://github.com/danielbruce/entypo/commit/b9097fc085f0c216af45d0f1335a0b8343ecb5e1

**Comment by krisbulman** [comment]
Cool! and here I was adding headers 1 by 1. glad this bug was spotted
